### ISSUE TITLE
Proposal: List of available kool scripts

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#111]
It would be good to have the possibility of showing all available kool scripts. It can be done through shell completion, a new command to list scripts or a flag `--list` on the `kool run`.

**Comment by fabriciojs** [comment]
@danielsuguimoto I like the idea of having the `kool run --list` to simply display the list of available scripts. 

After that, we could look into adding this behaviour to shell completion using the very `kool run --list`.

**Comment by dbpolito** [comment]
what if you run `kool run` withuot any other argument it prints all available scripts? is there a real need for adding `--list` ?

**Comment by danielsuguimoto** [comment]
@dbpolito if documented, sounds good to me as well!

**Comment by fabriciojs** [comment]
I usually don't like this behaviour, but it is usual in a bunch of CLI tools (no parameters, defaulting to listing available commands).

It is important to notice, as Cobra itself does something like this, the `kool run` is different since we are implementing it from scratch, so let's make sure the output is different to make clear it is a different list o commands than simply `kool` output for example.

**Comment by danielsuguimoto** [comment]
@dbpolito @fabriciojs why not both? Today, running `kool run` without arguments shows up an error, requiring at least one argument. We can customize this error to show the available scripts. And we can add the `--list` flag.

**Comment by fabriciojs** [comment]
If we do the `kool run`, I am okay not having `--list`.
