### ISSUE TITLE
kool logs prints "Attaching to" when no containers are running

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#150]
**Describe the bug**

When none of the containers are running and you try to run `kool logs`, the message `Attaching to` is showed up. Actually is the behavior from docker-compose.

**Kool version and environment**

kool version 1.3.0 on macOS environment

**To Reproduce**

- run kool stop
- run kool logs

**Expected behavior**

Should be nice to have a clear message about what really happened

**Screenshots**

![image](https://user-images.githubusercontent.com/25229545/95350815-f694de00-0896-11eb-8f93-5b47644eddb1.png)

**Comment by fabriciojs** [comment]
Thanks for the report!

I guess under logs, checking for running containers could a nice initial step. In case NO running containers, we display a previous warning (`No running containers.`). Still I think we should keep displaying the `docker-compose logs` output because if there is any stopped container (not removed), we could still have logs to see from it.

On a second topic, all docker-compose commands I believe should have an initial check for existing and valid `docker-compose.yml` in the current working directory. That is something that came to my mind now but we may handle in another issue.,

**Comment by danielsuguimoto** [comment]
@fabriciojs `kool stop` stops and removes all containers. So `docker-compose logs` has no containers to attach to, that's why it prints only `Attaching to`(seems that docker-compose is not validating empty array). So, I guess we need to check if there no containers at all and print `There are no containers` instead. I don't think we need to warn the user if containers are running or not. Avoiding this situation where all containers were stopped and removed is enough, IMO.
