### ISSUE TITLE
Show KOOL_VERSION on build_artifacts script

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#163]
It would be nice to print out the `KOOL_VERSION` variable value before start building the artifacts for a new release, just for double-checking on a release process.

**Comment by marti1125** [comment]
Hi 🖖  @danielsuguimoto  I would like to contribute 👍  where I have to add this print out?

**Comment by danielsuguimoto** [comment]
@marti1125 I guess at the end of the script. What do you think about it, @fabriciojs ?

**Comment by fabriciojs** [comment]
@marti1125 @danielsuguimoto 

I guess we could do even more - 

1. Right after the check for existing KOOL_VERSION, around line 13 (https://github.com/kool-dev/kool/blob/master/build_artifacts.sh#L13), we could add a confirmation since this is a manual process at the moment - `You are going to build all artfacts for version **X.X.X**. Continue? (y/N)` then have the user input `y` or `yes` in order to continue. (still could be automated at some point with `yes |`)

Then again at the end of the script, we could add as suggested a final message reinstating the version: `Finished building all artfacts for version **X.X.X**`.

**Comment by danielsuguimoto** [comment]
Sounds a good plan for me

**Comment by marti1125** [comment]
Hi @fabriciojs I created a new PR https://github.com/kool-dev/kool/pull/165 please check 😄

**Comment by fabriciojs** [comment]
PR merged onto master.
