### ISSUE TITLE
KOOL_ASUSER is being used on all images

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/kool#216]
We used to add that only to our images but at some time we lost it, we currently do that for custom images which doesn't handle well with `--user` set.

**Comment by fabriciojs** [comment]
@dbpolito where did you see this behaviour - like in `kool exec` or `kool docker`?

We only handled this in one place - `kool docker` and it is a very very weak check, since the image name parameter is not necessarily the first one, and we don't have a more evolved logic to tell which parameter is the image name.

**Comment by dbpolito** [comment]
`kool exec` on a custom image, not kool based.

**Comment by danielsuguimoto** [comment]
`docker-compose images` list the containers and the image repository. We could use it to create a logic for checking if the container is based on one of our images...I guess...

**Comment by fabriciojs** [comment]
> `docker-compose images` list the containers and the image repository. We could use it to create a logic for checking if the container is based on one of our images...I guess...

That is one thought, but we fall through on custom images (`build:`) even though the image might be kool-based, people might add more stuff to it.

**Comment by dbpolito** [comment]
i think we can solve this by not adding `--user` on docker-compose exec and add `user` on docker-compose... this might require some changes on entrypoint for starting services as sudo

**Comment by fabriciojs** [comment]
> i think we can solve this by not adding `--user` on docker-compose exec and add `user` on docker-compose... this might require some changes on entrypoint for starting services as sudo

1. I agree this seems a great way out. Even though we thought about it in the past we stopped and did not bother to solve the root start issue in the entrypoint, as now suggested.

2. A second though that raises just a bit o concern is: if people get the preset (with `user:` on docker-compose.yml) and then change the image, they will require further understanding about its behaviour to probably want to remove the `user:` entry. Possibly a minor thing we can live with, I guess.

**Comment by dbpolito** [comment]
well people changing stuff is always subject to break things... it's a hard problem to solve... we need a separate page on docs just to elaborate on this user thing we do and the whys... the problem and how we solve... maybe a section on a troubleshooting too...

**Comment by indiegenus** [comment]
To elaborate a bit more on how this surfaced again. I wanted to add Kool CLI to an existing project. The project already uses Docker and `docker-compose.yml`, and uses its own non-KoolDev Docker images. Adding Kool to the project was really quick and easy:
1. Installed the Kool binary
2. Created a new `kool.yml` in the project's `docker` folder
3. Added `KOOL_ASUSER=0` to the project's local `.env` file

I needed Daniel's assistance to add the 3rd step, because, without it, I was not able to use `kool run ...` commands successfully. It would have been that much quicker and easier to add Kool to the project if that 3rd step could be eliminated, or addressed better in the docs for Existing Project.

**Comment by fabriciojs** [comment]
There is a previous issue about the same issue, so closing this as duplicated. https://github.com/kool-dev/kool/issues/216

**Comment by fabriciojs** [comment]
Duplicated of https://github.com/kool-dev/kool/issues/166
