### ISSUE TITLE
'kool run compile' ignoring .env

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#48]
The command that is being exceuted: `docker run --init --rm -w /app -ti --volume /Users/jun/Opensource/kool:/app golang:1.15.0 go build -o kool`

I guess that the golang docker image is Linux based and we are not forwarding the local environment variables, but not 100% sure.

Obs: my local environment is MacOS based

**Comment by fabriciojs** [comment]
I am not sure I understand. What environment variables you would like to pass down the container? And .env is not something I ever considered supporting for compilation time.

Passing variables through for the container would require using `docker run -e ENV=VAL` in order to pass them down, which we don't do - and probably do not want to do for all variables.

So to clarify in the given situation:

- `docker` does have all the env environment available.
- `go build` does not have, since `docker run` did not pass down the variables with the `-e` option.

**Comment by fabriciojs** [comment]
Ahh I understand now, you mean for local development.

I guess in this case you can setup the `.env.dist` file with the options (Linux / MacOS) for GOOS, GOARCH, etc. Default to Linux.

Then ignore `.env`. Then update the `compile` script within `kool.yml` to pass down the necessary variables explicitly.

**Comment by fabriciojs** [comment]
This has been solved at current master and will go into the next release 1.0.17.
